import {
  codeExport as exporter,
  generateHooks,
  LanguageEmitterOpts,
  languageFromOpts,
} from "side-code-export";
import emitter from "./command";
import location from "./location";
import hooks from "./hook";
import { logger, terminateSuite, testSummary, testDeclaration } from "./utils";

export const withLogger = true;
export const displayName = "JavaScript New Relic Synthetics";

export const opts: LanguageEmitterOpts = {
  // @ts-ignore
  emitter: emitter,
  displayName,
  name: "javascript-newrelic-synthetics",
  hooks: generateHooks(hooks),
  fileExtension: ".js",
  commandPrefixPadding: "  ",
  commentPrefix: "//",
  logger: withLogger,
  generateMethodDeclaration: function generateMethodDeclaration() {
    return ``;
  },
  generateSuiteDeclaration: function generateSuiteDeclaration(name) {
    return `// Generated by New Relic SideKick exporter - ${name}
    ${logger(withLogger)}`;
  },
  generateTestDeclaration: function generateTestDeclaration(name: string) {
    return `// Test Start - ${name}
    ${testDeclaration(withLogger)}`;
  },
  generateTestCompletion() {
    return `${testSummary(withLogger)}`;
  },
  generateSuiteCompletion() {
    return `${terminateSuite(withLogger)}`;
  },
  generateFilename: function generateFilename(name: string) {
    return `${exporter.parsers.uncapitalize(
      exporter.parsers.sanitizeName(name)
    )}${opts.fileExtension}`;
  },
};

export default languageFromOpts(opts, location.emit);
